### ISSUE TITLE
UseDataStorage

### ISSUE THREAD

**Issue by sebastienrouif** [cnikolai/MoodTracker#1]
https://github.com/cnikolai/MoodTracker/blob/730d88888122e526e2f5d3010f9dfd8ceae5dd9e/app/src/main/java/com/nikolai/moodtracker/controller/MainActivity.java#L44
you should not have references to SharedPrefs in your activity or fragments but only access to DataStorage.
Same for the name of the shared prefs "com.nikolai.moodtracker.moodsharedprefs"

**Comment by cnikolai** [comment]
fixed
